name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    steps:
      - run: "git config --global core.autocrlf input"
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          config: .golangci.yml
          timeout: 10m
